`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: SoDonghwan
// 
// Create Date: 2024/09/09 17:21:51
// Design Name: 
// Module Name: spi_weight_write
// Project Name: 
// Target Devices: SRAM_weight SPI module
// Tool Versions: 
// Description: 
//              
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////
// 12/SEP - reset adding, port name changing, write_en port adding
// 15/SEP - If ADDR is 2**6 then memory module's input and spi module's output could be the 6bit? or 64bit?

module sram_weight_write_v1 
#(
    parameter addr_width = 10,
    parameter data_width = 128,
    parameter wr_delay = 8
)
(
    input       rstb,
    input       sram_sclk,              // clk generated by FPGA
    input       sram_ss,               // ss  generated by FPGA
    input       sram_sdata,
    input       seq_start,
    input [2:0] seq_state,
    
    output  reg [addr_width-1:0] sram_addr,
    output  reg [data_width-1:0] sram_data,
    output  reg sram_clk,             // sram write en 
    output  reg sram_web,
    output  reg sram_ceb
);
    reg [7:0] counter_w;
    reg [addr_width+data_width:0] data_w;
    reg [1:0] state_w;

    localparam                          ST_IDLE     =   0,
                                         ST_CAP     =   1,
                                         ST_STORE   =   2,
                                         ST_WAIT    =   3;
                                         
    always @(negedge sram_sclk or negedge rstb) begin
        if(!rstb) begin
            counter_w <= 0;
            data_w <= 0;
            sram_clk <= 0;
            sram_web <= 1;
            sram_ceb <= 1;
            sram_addr <= 0;
            sram_data <= 0;
            state_w <= ST_IDLE;
        end
        else begin
            case(state_w)
                ST_IDLE : begin // 0
                    sram_web <= 1;
                    sram_ceb <= 1;
                    if (seq_state == 1 & seq_start == 1) begin
                        state_w <= ST_CAP;
                    end
                end
                ST_CAP : begin // 1
                    if (counter_w < addr_width + data_width + 1) begin               
                        data_w <= data_w << 1;       
                        data_w[0] <= sram_sdata;                       
                        if (counter_w == wr_delay) sram_clk <= 0; 
                    end
                    counter_w <= counter_w + 1; 
                    if (sram_ss) begin
                        state_w <= ST_STORE;  
                        counter_w <= 0;
                        data_w <= 0;
                        sram_clk <= 0;
                        sram_addr <= data_w[addr_width+data_width-1:data_width];   
                        sram_data <= data_w[data_width-1:0];
                        state_w <= ST_STORE;
                        sram_web <= 0;
                        sram_ceb <= 0;
                    end          
                end
                ST_STORE : begin // 2
//                    sram_web <= 1;
//                    sram_ceb <= 1;
//                    state_w <= ST_IDLE;
                    counter_w <= counter_w + 1;
                    if (counter_w == 3) sram_clk <= 1;
                    else if ( counter_w == 5) begin
                        sram_web <= 1;
                        sram_ceb <= 1;
                        state_w <= ST_IDLE;
                        counter_w <= 0;
                        sram_clk <= 0;
                    end
                end

            endcase
        end
    end
endmodule
