`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 2024/12/03 21:44:00
// Design Name: 
// Module Name: sram_feature_write_v0
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////


module sram_feature_write_v0
#(
    parameter total_width = 168,
    parameter addr_width = 10,
    parameter data_width = 128,
    parameter wr_delay = 6
)
(
    input       rstb,
    input       sram_sclk,              // clk generated by FPGA
    input       sram_ss,               // ss  generated by FPGA
    input       sram_sdata,
    input       wr_feature_on,
    
    output  reg sram_clk,  
    output  reg [data_width-1:0] sram_data,
    output  reg [addr_width-1:0] sram_addr,
    output  reg sram_ceb,
    output  reg sram_web,  
    output  reg sram_mux,
    
    output  reg start_nn
);
    reg [7:0] counter;
    reg [1:0] state;
    reg [4:0] addr_con;
    
    reg [total_width-1:0] total_data;
    
    localparam                          ST_IDLE             =       0,
                                                    ST_CAP              =       1,
                                                    ST_STORE         =       2,
                                                    ST_NN               =       3;
 
    
    always @(negedge sram_sclk or negedge rstb) begin
        if(!rstb) begin
            counter <= 0;
            state <= 0;
            addr_con <= 0;
            total_data <= 0;
            sram_clk <= 0;
            sram_web <= 0;
            sram_ceb <= 0;
            sram_addr <= 0;
            sram_data <= 0;
            start_nn <= 0;
            sram_mux <= 0;
        end
        else begin
            case(state)
                ST_IDLE : begin 
                    sram_ceb <= 1;
                    sram_web <= 1;
                    if(wr_feature_on) begin 
                        state <= ST_CAP;
                        counter <= 0;
                    end
                end
                 ST_CAP : begin 
                    if(sram_ss) begin 
                        state <= ST_STORE;
                        counter <= 0;
                    end
                    else begin 
                        total_data <= total_data  << 1;
                        total_data[0] <= sram_sdata;
                    end
                end
                ST_STORE : begin 
                    sram_mux <= 1;
                    sram_ceb <= 0;
                    sram_web <= 0;
                    counter <= counter + 1;
                    
                    if(counter == 0) begin 
                        sram_data <= {total_data[167:144],{104{1'b0}}};
                        sram_addr <= addr_con;
                        addr_con <= addr_con + 1;
                    end
                    else if(counter == 0 + 2) begin 
                        sram_clk <= 1;
                    end
                    else if(counter == 0 + 4) begin 
                        sram_clk <= 0;
                    end
                    
                    else if(counter == wr_delay * 1) begin 
                        sram_data <= {total_data[143:120],{104{1'b0}}};
                        sram_addr <= addr_con;
                        addr_con <= addr_con + 1;
                    end
                    else if(counter == wr_delay * 1 + 2) begin 
                        sram_clk <= 1;
                    end
                    else if(counter == wr_delay * 1 + 4) begin 
                        sram_clk <= 0;
                    end
                    
                    else if(counter == wr_delay * 2) begin 
                        sram_data <= {total_data[119:96],{104{1'b0}}};
                        sram_addr <= addr_con;
                        addr_con <= addr_con + 1;
                    end
                    else if(counter == wr_delay * 2 + 2) begin 
                        sram_clk <= 1;
                    end
                    else if(counter == wr_delay * 2 + 4) begin 
                        sram_clk <= 0;
                    end
                    
                    else if(counter == wr_delay * 3) begin 
                        sram_data <= {total_data[95:72],{104{1'b0}}};
                        sram_addr <= addr_con;
                        addr_con <= addr_con + 1;
                    end
                    else if(counter == wr_delay * 3 + 2) begin 
                        sram_clk <= 1;
                    end
                    else if(counter == wr_delay * 3 + 4) begin 
                        sram_clk <= 0;
                    end
                    
                    else if(counter == wr_delay * 4) begin 
                        sram_data <= {total_data[71:48],{104{1'b0}}};
                        sram_addr <= addr_con;
                        addr_con <= addr_con + 1;
                    end
                    else if(counter == wr_delay * 4 + 2) begin 
                        sram_clk <= 1;
                    end
                    else if(counter == wr_delay * 4 + 4) begin 
                        sram_clk <= 0;
                    end
                    
                    else if(counter == wr_delay * 5) begin 
                        sram_data <= {total_data[47:24],{104{1'b0}}};
                        sram_addr <= addr_con;
                        addr_con <= addr_con + 1;
                    end
                    else if(counter == wr_delay * 5 + 2) begin 
                        sram_clk <= 1;
                    end
                    else if(counter == wr_delay * 5 + 4) begin 
                        sram_clk <= 0;
                    end
                    
                    else if(counter == wr_delay * 6) begin 
                        sram_data <= {total_data[23:0],{104{1'b0}}};
                        sram_addr <= addr_con;
                        if(addr_con == 20) begin 
                            addr_con <= 0;
                        end
                        else begin 
                            addr_con <= addr_con + 1;
                        end
                    end
                    else if(counter == wr_delay * 6 + 2) begin 
                        sram_clk <= 1;
                    end
                    else if(counter == wr_delay * 6 + 4) begin 
                        sram_clk <= 0;
                    end
                    else if(counter == wr_delay * 7) begin 
                        state <= ST_NN;
                        start_nn <= 1;
                        sram_mux <= 0;
                        sram_ceb <= 1;
                        sram_web <= 1;
                    end
                end
                ST_NN : begin 
                    state <= ST_IDLE;
                    start_nn <= 0;
                end
            endcase
        end
    end
endmodule
