`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: SoDonghwan
// 
// Create Date: 2024/09/09 17:21:51
// Design Name: 
// Module Name: spi_weight_write
// Project Name: 
// Target Devices: SRAM_weight SPI module
// Tool Versions: 
// Description: 
//              
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////
// 12/SEP - reset adding, port name changing, write_en port adding
// 15/SEP - If ADDR is 2**6 then memory module's input and spi module's output could be the 6bit? or 64bit?

module sram_weight_write_v0 
#(
    parameter addr_width = 10,
    parameter data_width = 128,
    parameter wr_delay = 6
)
(
    input       rstb,
    input       sram_sclk,              // clk generated by FPGA
    input       sram_ss,               // ss  generated by FPGA
    input       sram_sdata,
    input       wr_weight_on,
    
    output  reg [addr_width-1:0] sram_addr,
    output  reg [data_width-1:0] sram_data,
    output  reg sram_clk,             // sram write en 
    output  reg sram_web,
    output  reg sram_ceb
);
    reg [7:0] counter;
    reg [addr_width+data_width:0] data;
        
    always @(negedge sram_sclk or negedge rstb) begin
        if(!rstb) begin
            counter <= 0;
            data <= 0;
            sram_clk <= 0;
            sram_web <= 0;
            sram_ceb <= 0;
            sram_addr <= 0;
            sram_data <= 0;
        end
        else begin
            if (wr_weight_on) begin
                sram_web <= 0;
                sram_ceb <= 0;
            end
            else begin 
                sram_web <= 1;
                sram_ceb <= 1;
            end
            if (sram_ss) begin  
                counter <= 0;
                data <= 0;
                sram_clk <= 0;
                sram_addr <= data[addr_width+data_width-1:data_width];   
                sram_data <= data[data_width-1:0];
            end
            else begin
                if (counter < addr_width + data_width+1) begin               
                    data <= data << 1;       
                    data[0] <= sram_sdata;                       
                    if (counter == wr_delay*2) sram_clk <= 1; 
                    else if (counter == wr_delay*6) sram_clk <= 0;             
                end
                counter <= counter + 1;
            end
        end
    end
endmodule
