###################################################################

# Created by write_sdc on Sun Jun 15 19:00:14 2025

###################################################################
set sdc_version 2.1

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current uA
set_max_area 0
set_ideal_network [get_ports rst_n]
create_clock [get_ports clk]  -period 5  -waveform {0 2.5}
set_clock_uncertainty -setup 1.75  [get_clocks clk]
set_input_delay -clock clk  1.3  [get_ports clk]
set_input_delay -clock clk  1.3  [get_ports rst_n]
set_input_delay -clock clk  1.3  [get_ports pe_en]
set_input_delay -clock clk  1.3  [get_ports {data_in_r[7]}]
set_input_delay -clock clk  1.3  [get_ports {data_in_r[6]}]
set_input_delay -clock clk  1.3  [get_ports {data_in_r[5]}]
set_input_delay -clock clk  1.3  [get_ports {data_in_r[4]}]
set_input_delay -clock clk  1.3  [get_ports {data_in_r[3]}]
set_input_delay -clock clk  1.3  [get_ports {data_in_r[2]}]
set_input_delay -clock clk  1.3  [get_ports {data_in_r[1]}]
set_input_delay -clock clk  1.3  [get_ports {data_in_r[0]}]
set_input_delay -clock clk  1.3  [get_ports {data_in_g[7]}]
set_input_delay -clock clk  1.3  [get_ports {data_in_g[6]}]
set_input_delay -clock clk  1.3  [get_ports {data_in_g[5]}]
set_input_delay -clock clk  1.3  [get_ports {data_in_g[4]}]
set_input_delay -clock clk  1.3  [get_ports {data_in_g[3]}]
set_input_delay -clock clk  1.3  [get_ports {data_in_g[2]}]
set_input_delay -clock clk  1.3  [get_ports {data_in_g[1]}]
set_input_delay -clock clk  1.3  [get_ports {data_in_g[0]}]
set_input_delay -clock clk  1.3  [get_ports {data_in_b[7]}]
set_input_delay -clock clk  1.3  [get_ports {data_in_b[6]}]
set_input_delay -clock clk  1.3  [get_ports {data_in_b[5]}]
set_input_delay -clock clk  1.3  [get_ports {data_in_b[4]}]
set_input_delay -clock clk  1.3  [get_ports {data_in_b[3]}]
set_input_delay -clock clk  1.3  [get_ports {data_in_b[2]}]
set_input_delay -clock clk  1.3  [get_ports {data_in_b[1]}]
set_input_delay -clock clk  1.3  [get_ports {data_in_b[0]}]
set_input_delay -clock clk  1.3  [get_ports {weight_in[7]}]
set_input_delay -clock clk  1.3  [get_ports {weight_in[6]}]
set_input_delay -clock clk  1.3  [get_ports {weight_in[5]}]
set_input_delay -clock clk  1.3  [get_ports {weight_in[4]}]
set_input_delay -clock clk  1.3  [get_ports {weight_in[3]}]
set_input_delay -clock clk  1.3  [get_ports {weight_in[2]}]
set_input_delay -clock clk  1.3  [get_ports {weight_in[1]}]
set_input_delay -clock clk  1.3  [get_ports {weight_in[0]}]
set_input_delay -clock clk  1.3  [get_ports layer_start]
set_output_delay -clock clk  1.3  [get_ports pe_done]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_r[19]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_r[18]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_r[17]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_r[16]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_r[15]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_r[14]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_r[13]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_r[12]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_r[11]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_r[10]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_r[9]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_r[8]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_r[7]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_r[6]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_r[5]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_r[4]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_r[3]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_r[2]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_r[1]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_r[0]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_g[19]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_g[18]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_g[17]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_g[16]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_g[15]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_g[14]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_g[13]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_g[12]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_g[11]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_g[10]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_g[9]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_g[8]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_g[7]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_g[6]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_g[5]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_g[4]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_g[3]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_g[2]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_g[1]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_g[0]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_b[19]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_b[18]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_b[17]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_b[16]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_b[15]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_b[14]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_b[13]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_b[12]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_b[11]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_b[10]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_b[9]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_b[8]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_b[7]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_b[6]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_b[5]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_b[4]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_b[3]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_b[2]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_b[1]}]
set_output_delay -clock clk  1.3  [get_ports {result_out_flat_b[0]}]
