`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: SoDonghwan
// 
// Create Date: 2024/09/09 17:21:51
// Design Name: 
// Module Name: spi_weight_write
// Project Name: 
// Target Devices: SRAM_weight SPI module
// Tool Versions: 
// Description: 
//              
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////
// 12/SEP - reset adding, port name changing, write_en port adding
// 15/SEP - If ADDR is 2**6 then memory module's input and spi module's output could be the 6bit? or 64bit?

module sram_weight_write 
#(
    parameter addr_width = 8,
    parameter data_width = 256,
    parameter wr_delay = 3
)
(
    input       rstb,
    input       rf_sclk,              // clk generated by FPGA
    input       rf_ss,               // ss  generated by FPGA
    input       rf_sdata,
    input       wr_weight_on,
    
    output  reg [addr_width-1:0] rf_addr,
    output  reg [data_width-1:0] rf_data,
    output  reg rf_clk,             // sram write en 
    output  reg rf_web,
    output  reg rf_ceb
);
    reg [7:0] counter;
    reg [addr_width+data_width:0] data;
        
    always @(negedge rf_sclk or posedge rf_ss or negedge rstb) begin
        if(!rstb) begin
            counter <= 0;
            data <= 0;
            rf_clk <= 0;
            rf_web <= 1;
            rf_ceb <= 1;
            rf_addr <= 0;
            rf_data <= 0;
        end
        else begin
            if (wr_weight_on) begin
                rf_web <= 0;
                rf_ceb <= 0;
            end
            else begin 
                rf_web <= 1;
                rf_ceb <= 1;
            end
            if (rf_ss) begin  
                counter <= 0;
                data <= 0;
                rf_clk <= 0;
                rf_addr <= data[addr_width+data_width-1:data_width];   
                rf_data <= data[data_width-1:0];
            end
            else begin
                if (counter < addr_width + data_width+1) begin               
                    data <= data << 1;       
                    data[0] <= rf_sdata;                       
                    if (counter == wr_delay) rf_clk <= 1;             
                end
                counter <= counter + 1;
            end
        end
    end
endmodule
