`timescale 1ns/1ps


module top_dscnn_wrapper #(
    parameter WEIGHT_BIT = 8,
    parameter INPUT_BIT = 8,
    parameter NUM_CHANNEL = 32
)(
    // Global input
    input rstb,
    input clk, 
    
    //ib stands for input buffer
    //sharing sclk with rf_sclk
    input ib_ss,
    input ib_sdata,
    input wr_input_on,

    //input from SPI network
    input rf_sclk,              // clk generated by FPGA
    input rf_ss,               // ss  generated by FPGA
    input rf_sdata,
    input wr_weight_on,

    output valid_o,
    output [3:0] decision_o
);

    wire [1:0] state;
    wire [3:0] ib_addr_ctrl;
    wire ib_ceb_ctrl;
    wire ib_web_ctrl;
    wire calc_en_i;

    ib_ctrl ib_controller(
        // Global input
        .rstb(rstb),
        .clk(clk), 
        
        .wr_input_on(wr_input_on),

        .state(state),
        .ib_addr(ib_addr_ctrl),
        .ib_ceb(ib_ceb_ctrl),
        .ib_web(ib_web_ctrl),
        .calc_en(calc_en_i)
    );

    localparam WR_DELAY = 3;

    wire [3:0] ib_addr_spi;
    wire [INPUT_BIT-1:0] ib_data;
    wire ib_clk_spi;
    wire ib_web_spi;
    wire ib_ceb_spi;

    sram_weight_write #(
        .addr_width($clog2(10)),
        .data_width(INPUT_BIT),
        .wr_delay(WR_DELAY)
    ) spi_input_buffer (
        .rstb(rstb),
        .rf_sclk(rf_sclk),
        .rf_ss(ib_ss),
        .rf_sdata(ib_sdata),
        .wr_weight_on(wr_input_on),
        .rf_addr(ib_addr_spi),
        .rf_data(ib_data),
        .rf_clk(ib_clk_spi),
        .rf_web(ib_web_spi),
        .rf_ceb(ib_ceb_spi)
    );

    wire [INPUT_BIT-1:0] data_i;
    wire ib_clk_i;
    wire ib_ceb_i;
    wire ib_web_i;
    wire [3:0] ib_addr_i;

    assign ib_clk_i = (state[0]) ? clk : ib_clk_spi;
    assign ib_ceb_i = (state[0]) ? ib_ceb_ctrl : ib_ceb_spi;
    assign ib_web_i = (state[0]) ? ib_web_ctrl : ib_web_spi;
    assign ib_addr_i = (state[0]) ? ib_addr_ctrl : ib_addr_spi;

    input_buffer #(.ADDRESS_BIT(4), .WORD_LENGTH(INPUT_BIT)) ib (
        .clk(ib_clk_i),
        .ceb(ib_ceb_i),
        .web(ib_web_i),
        .addr(ib_addr_i),
        .d(ib_data),
        .q(data_i)
    );

    top_dscnn #(
            .WEIGHT_BIT(WEIGHT_BIT),
            .INPUT_BIT(INPUT_BIT),
            .NUM_CHANNEL(NUM_CHANNEL)
        ) dscnn_top (
            .rstb(rstb),
            .clk(clk),

            .calc_en_i(calc_en_i),
            .data_i(data_i),

            .rf_sclk(rf_sclk),
            .rf_ss(rf_ss),
            .rf_sdata(rf_sdata),
            .wr_weight_on(wr_weight_on),
            .valid_o(valid_o),
            .decision_o(decision_o)
        );

endmodule
