`timescale 1ns / 1ps

module top_dscnn #(
    parameter WEIGHT_BIT = 8,
    parameter INPUT_BIT = 8,
    parameter NUM_CHANNEL = 32
)(
    // Global input
    input rstb,
    input clk, 
    // Control Signal for Weight Initialization    
    // input en_i, // enable to turn on the module
    input calc_en_i, // FE Done -> Layer1 Begin
    input [INPUT_BIT-1:0] data_i,
    
    //input from SPI network
    input rf_sclk,              // clk generated by FPGA
    input rf_ss,               // ss  generated by FPGA
    input rf_sdata,
    input wr_weight_on,

    output valid_o,
    output [3:0] decision_o
);

    //controller localparam
    localparam IM_BIT_LEN = $clog2(100);
    localparam MA_BIT_LEN = $clog2(16);
    localparam MB_BIT_LEN = $clog2(20);
    localparam WM_BIT_LEN = $clog2(144);

    //controller wires
    //wire weight_done;
    //wire weight_buf_rst;
    //wire [NUM_CHANNEL-1:0] weight_buf_en;
    wire [WM_BIT_LEN-1:0] wm_addr_ctrl;
    wire wm_web_ctrl;
    wire wm_ceb_ctrl;
    wire [IM_BIT_LEN-1:0] im_addr;
    wire im_web;
    wire im_ceb;
    wire [MA_BIT_LEN-1:0] ma_addr;
    wire ma_web;
    wire ma_ceb;
    wire [MB_BIT_LEN-1:0] mb_addr;
    wire mb_web;
    wire mb_ceb;
    wire pe_en;
    wire pe_rst;
    wire [31:0] out_buf_en;
    wire out_buf_sel;
    wire out_buf_rst;
    wire pool_sel; 
    wire comp_start;
    //wire rf_sel;
    wire [2:0] layer;
    wire done;

    //controller module
    controller_top #(
        .IM_BIT_LEN(IM_BIT_LEN),       // $clog2(100) = 7
        .MA_BIT_LEN(MA_BIT_LEN),       // $clog2(16) = 4
        .MB_BIT_LEN(MB_BIT_LEN),       // $clog2(20) = 5
        .WM_BIT_LEN(WM_BIT_LEN)        // $clog2(144) = 8
    ) controller_module (
        .rstb(rstb),
        .clk(clk),
        //.en(en_i),
        .wr_weight_on(wr_weight_on),
        .calc_en(calc_en_i),
        //.weight_done(weight_done),
        //.weight_buf_rst_o(weight_buf_rst),
        //.weight_buf_en_o(weight_buf_en),
        .wm_addr_o(wm_addr_ctrl),
        .wm_web_o(wm_web_ctrl),
        .wm_ceb_o(wm_ceb_ctrl),
        .im_addr_o(im_addr),
        .im_web_o(im_web),
        .im_ceb_o(im_ceb),
        .ma_addr_o(ma_addr),
        .ma_web_o(ma_web),
        .ma_ceb_o(ma_ceb),
        .mb_addr_o(mb_addr),
        .mb_web_o(mb_web),
        .mb_ceb_o(mb_ceb),
        .pe_en_o(pe_en),
        .pe_rst_o(pe_rst),
        .out_buf_en_o(out_buf_en),
        .out_buf_sel_o(out_buf_sel),
        .out_buf_rst_o(out_buf_rst),
        .pool_sel_o(pool_sel),
        .comp_start_o(comp_start),
        //.rf_sel_o(rf_sel),
        .layer(layer),
        .done_o(done)
    );

    // parameter for spi interface module
    localparam WR_DELAY = 3;

    // wires fro spi interface module
    wire [WM_BIT_LEN-1:0] wm_addr_spi;
    wire [WEIGHT_BIT*NUM_CHANNEL-1:0] wm_d;
    wire wm_clk_spi;
    wire wm_web_spi;
    wire wm_ceb_spi;
    
    sram_weight_write #(
        .addr_width(WM_BIT_LEN),
        .data_width(WEIGHT_BIT*NUM_CHANNEL),
        .wr_delay(WR_DELAY)
    ) sram_weight_write_inst (
        .rstb(rstb),
        .rf_sclk(rf_sclk),
        .rf_ss(rf_ss),
        .rf_sdata(rf_sdata),
        .wr_weight_on(wr_weight_on),
        .rf_addr(wm_addr_spi),
        .rf_data(wm_d),
        .rf_clk(wm_clk_spi),
        .rf_web(wm_web_spi),
        .rf_ceb(wm_ceb_spi)
    );

    // Wire assignment for WM input
    wire wm_clk_i;
    wire wm_ceb_i;
    wire wm_web_i;
    wire [WM_BIT_LEN-1:0] wm_addr_i;

    assign wm_clk_i = (wr_weight_on) ? wm_clk_spi: clk;
    assign wm_ceb_i = (wr_weight_on) ? wm_ceb_spi: wm_ceb_ctrl;
    assign wm_web_i = (wr_weight_on) ? wm_web_spi: wm_web_ctrl;
    assign wm_addr_i = (wr_weight_on) ? wm_addr_spi: wm_addr_ctrl;

    localparam MEM_WORD_LENGTH = 128;

    //WM wire assignment
    wire [MEM_WORD_LENGTH-1:0] wm_q_high;
    wire [MEM_WORD_LENGTH-1:0] wm_q_low;
    wire [NUM_CHANNEL*WEIGHT_BIT-1:0] wm_q;

    register_file #(.ADDRESS_BIT(WM_BIT_LEN), .WORD_LENGTH(MEM_WORD_LENGTH)) wm_high (
        .CLK(wm_clk_i),
        .CEB(wm_ceb_i),
        .WEB(wm_web_i),
        .A(wm_addr_i),
        .D(wm_d[$left(wm_d) -: (WEIGHT_BIT*NUM_CHANNEL/2)]),
        .Q(wm_q_high)
    );

    register_file #(.ADDRESS_BIT(WM_BIT_LEN), .WORD_LENGTH(MEM_WORD_LENGTH)) wm_low (
        .CLK(wm_clk_i),
        .CEB(wm_ceb_i),
        .WEB(wm_web_i),
        .A(wm_addr_i),
        .D(wm_d[(WEIGHT_BIT*NUM_CHANNEL/2)-1 -: (WEIGHT_BIT*NUM_CHANNEL/2)]),
        .Q(wm_q_low)
    );

    assign wm_q = {wm_q_high, wm_q_low};


    //MA wire assignment
    wire [MEM_WORD_LENGTH-1:0] ma_q_high;
    wire [MEM_WORD_LENGTH-1:0] ma_q_low;
    wire [MEM_WORD_LENGTH-1:0] ma_d_high;
    wire [MEM_WORD_LENGTH-1:0] ma_d_low;
    wire [NUM_CHANNEL*WEIGHT_BIT-1:0] ma_q;

    register_file #(.ADDRESS_BIT(MA_BIT_LEN), .WORD_LENGTH(MEM_WORD_LENGTH)) ma_high (
        .CLK(clk),
        .CEB(ma_ceb),
        .WEB(ma_web),
        .A(ma_addr),
        .D(ma_d_high),
        .Q(ma_q_high)
    );

    register_file #(.ADDRESS_BIT(MA_BIT_LEN), .WORD_LENGTH(MEM_WORD_LENGTH)) ma_low (
        .CLK(clk),
        .CEB(ma_ceb),
        .WEB(ma_web),
        .A(ma_addr),
        .D(ma_d_low),
        .Q(ma_q_low)
    );

    assign ma_q = {ma_q_high, ma_q_low};

    //MB wire assignment
    wire [MEM_WORD_LENGTH-1:0] mb_q_high;
    wire [MEM_WORD_LENGTH-1:0] mb_q_low;
    wire [MEM_WORD_LENGTH-1:0] mb_d_high;
    wire [MEM_WORD_LENGTH-1:0] mb_d_low;
    wire [NUM_CHANNEL*WEIGHT_BIT-1:0] mb_q;

    register_file #(.ADDRESS_BIT(MB_BIT_LEN), .WORD_LENGTH(MEM_WORD_LENGTH)) mb_high (
        .CLK(clk),
        .CEB(mb_ceb),
        .WEB(mb_web),
        .A(mb_addr),
        .D(mb_d_high),
        .Q(mb_q_high)
    );

    register_file #(.ADDRESS_BIT(MB_BIT_LEN), .WORD_LENGTH(MEM_WORD_LENGTH)) mb_low (
        .CLK(clk),
        .CEB(mb_ceb),
        .WEB(mb_web),
        .A(mb_addr),
        .D(mb_d_low),
        .Q(mb_q_low)
    );

    assign mb_q = {mb_q_high, mb_q_low};

    //IM wire assignment
    wire [INPUT_BIT-1:0] im_q_tmp;
    wire [NUM_CHANNEL*WEIGHT_BIT-1:0] im_q;

    register_file #(.ADDRESS_BIT(WM_BIT_LEN), .WORD_LENGTH(8)) input_memory (
        .CLK(clk),
        .CEB(im_ceb),
        .WEB(im_web),
        .A(im_addr),
        .D(data_i),
        .Q(im_q_tmp)
    );
    
    assign im_q = {32{im_q_tmp}};

    wire [NUM_CHANNEL*WEIGHT_BIT-1:0] pe_data_i;

    layer_mux #(
        .WORD_LENGTH(NUM_CHANNEL*WEIGHT_BIT)
    ) layer_mux (
        .layer(layer),
        .im_q(im_q),
        .ma_q(ma_q),
        .mb_q(mb_q),
        .data_o(pe_data_i)
    );


    wire [INPUT_BIT-1:0] pe_data_sliced [0:NUM_CHANNEL-1];
    wire [WEIGHT_BIT-1:0] pe_weight_sliced [0:NUM_CHANNEL-1];
    //pe_data_i, pe_weight_i slicing
    genvar i;
    generate
        for (i=0; i<NUM_CHANNEL; i=i+1) begin
            assign pe_data_sliced[i] = pe_data_i[(i+1)*INPUT_BIT-1 -: INPUT_BIT];
            assign pe_weight_sliced[i] = wm_q[(i+1)*WEIGHT_BIT-1 -: WEIGHT_BIT];
        end
    endgenerate

    //parameter for PE
    localparam INT_EXTEND = $clog2(288);

    //wire for PE
    wire [(INPUT_BIT+WEIGHT_BIT+INT_EXTEND)-1:0] pe_o [0:NUM_CHANNEL-1];

    pe_arr #(.DATA_WIDTH(INPUT_BIT),
        .WEIGHT_WIDTH(WEIGHT_BIT),
        .INT_EXTEND(INT_EXTEND), 
        .WEIGHT_INT_WIDTH(5), // TBD
        .PE_NUM(NUM_CHANNEL)
    ) pe_arr_inst (
        .clk(clk),
        .rstb(rstb),
        .en(pe_en),
        .rst_local(pe_rst),
        .sel(out_buf_sel),
        .data_i(pe_data_sliced),
        .weight_i(pe_weight_sliced),
        .data_o(pe_o)
    );

    wire [(INPUT_BIT+WEIGHT_BIT+INT_EXTEND)-1:0] adder_tree_o;

    adder_tree #(
        .INPUT_WIDTH(INPUT_BIT),
        .WEIGHT_WIDTH(WEIGHT_BIT),
        .INT_EXTEND(INT_EXTEND)
    ) adder_tree_inst (
        .sel(out_buf_sel),
        .data_i(pe_o),
        .data_o(adder_tree_o)
    );

    wire [INPUT_BIT-1:0] out_buf_o [0:NUM_CHANNEL-1];

    output_buf #(
        .INPUT_WIDTH(INPUT_BIT),
        .WEIGHT_WIDTH(WEIGHT_BIT),
        .INT_EXTEND(INT_EXTEND),
        .PE_NUM(NUM_CHANNEL),
        .INPUT_INT_WIDTH(5), // TBD
        .WEIGHT_INT_WIDTH(5) // TBD
    ) output_buf_inst (
        .clk(clk),
        .rstb(rstb),
        .rst_local(out_buf_rst),
        .sel(out_buf_sel),
        .en_in(out_buf_en),
        .data_i(pe_o),
        .adder_i(adder_tree_o),
        .data_o(out_buf_o)
    );

    
    wire [127:0] out_buf_high;
    wire [127:0] out_buf_low;

    // Assign each 8-bit segment to the corresponding position in `data`
    genvar j;
    generate
        for (j=0; j<16; j=j+1) begin
            assign out_buf_high[(j+1)*INPUT_BIT-1 -: INPUT_BIT] = out_buf_o[j+16];
            assign out_buf_low[(j+1)*INPUT_BIT-1 -: INPUT_BIT] = out_buf_o[j];
        end
    endgenerate

    assign ma_d_high = out_buf_high;
    assign ma_d_low = out_buf_low;

    assign mb_d_high = out_buf_high;
    assign mb_d_low = out_buf_low;

    localparam NUM_CLASS = 7;

    wire [3:0] decision;
    wire valid_out;

    comparator #(
        .INPUT_BITS(INPUT_BIT),
        .NUM_CLASS(NUM_CLASS)
    ) comparator_inst (
        .clk(clk),
        .rstb(rstb),
        .valid_in(comp_start),
        .in_data(out_buf_o[0:NUM_CLASS-1]),
        .decision(decision),
        .valid_out(valid_out)
    );


    assign decision_o = decision;
    assign valid_o = valid_out;


endmodule
